steps:
  - id: get_terraform_plan
    name: gcr.io/cloud-builders/gsutil
    args:
      [
        "cp",
        "gs://${PROJECT_ID}-terraform-planfiles/planfile-$COMMIT_SHA",
        "planfile",
      ]
    waitFor: ["-"]

  - id: terraform_init
    env:
      - TF_IN_AUTOMATION=true
    name: hashicorp/terraform:1.0.11
    args:
      [
        "init",
        "-reconfigure",
        "-backend-config",
        "bucket=${PROJECT_ID}-terraform-state",
      ]
    secretEnv: ["GOOGLE_CREDENTIALS"]

  - id: terraform_show_plan
    env:
      - TF_IN_AUTOMATION=true
    name: hashicorp/terraform:1.0.11
    args: ["show", "planfile"]

  - id: terraform_apply
    env:
      - TF_IN_AUTOMATION=true
    name: hashicorp/terraform:1.0.11
    args: ["apply", "-parallelism", "2", "planfile"]
    timeout: 3600s
    secretEnv:
      ["GOOGLE_CREDENTIALS"]


availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/$_GOOGLE_CREDENTIALS/versions/latest
      env: "GOOGLE_CREDENTIALS"
timeout: 3600s
# options:
#   machineType: "E2_HIGHCPU_32"
