steps:
  - id: terraform_init
    env:
      - TF_IN_AUTOMATION=true
    name: hashicorp/terraform:1.0.11
    args:
      [
        "init",
        "-reconfigure",
        "-backend-config",
        "bucket=${PROJECT_ID}-tfstate",
      ]
    secretEnv: ["GOOGLE_CREDENTIALS"]

  - id: terraform_destroy
    env:
      - TF_IN_AUTOMATION=true
    name: hashicorp/terraform:1.0.11
    args: ["destroy", "--auto-approve"]
    timeout: 3600s
    secretEnv: ["GOOGLE_CREDENTIALS"]


availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CREDENTIALS/versions/latest
      env: "GOOGLE_CREDENTIALS"
timeout: 3600s
